// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void clear_pressed(lv_event_t * e);
void blue_pressed(lv_event_t * e);
void start_event(lv_event_t * e);
void stop_event(lv_event_t * e);
void brightnessInc(lv_event_t * e);
void brightnessDec(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
