// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"
#include "lcd_util.h" 
extern uint8_t brightness;
extern uint8_t can_start;
extern uint32_t frame_count;
uint8_t buff[20];


void yellow_pressed(lv_event_t * e)
{
	// Your code here
}

void blue_pressed(lv_event_t * e)
{
	// Your code here
}

void start_event(lv_event_t * e)
{
	can_start = 1;
}

void stop_event(lv_event_t * e)
{
	can_start = 0;
}

void brightnessInc(lv_event_t * e)
{
	brightness = brightness + 1;
	if (brightness>10)brightness =10;
  Set_Backlight_480(brightness);

	sprintf(buff,"Brightness %d",brightness); 
  lv_label_set_text(ui_brightness,buff);
}

void brightnessDec(lv_event_t * e)
{
	brightness = brightness - 1;
	if (brightness < 1)brightness =1;
  Set_Backlight_480(brightness);
	
	sprintf(buff,"Brightness %d",brightness); 
  lv_label_set_text(ui_brightness,buff);
}

void clear_pressed(lv_event_t * e)
{
	frame_count = 0;
}
