// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_clear;
lv_obj_t *uic_ccCANlen;
lv_obj_t *uic_ccCANID;
lv_obj_t *uic_canFDLen;
lv_obj_t *uic_canfdID;
lv_obj_t *uic_brightnessDec;
lv_obj_t *uic_brightnessInc;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Spinner1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_version = NULL;lv_obj_t *ui_brightness = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_brightnessInc = NULL;lv_obj_t *ui_brightnessDec = NULL;lv_obj_t *ui_labelbright = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_canfdData = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_ClassicCANdata = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_canfdID = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_canFDLen = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_ccCANID = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_ccCANlen = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_framecount = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_clear = NULL;
// event funtions
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      clear_pressed( e );
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      blue_pressed( e );
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      start_event( e );
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      stop_event( e );
}
}

void ui_event_brightnessInc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      brightnessInc( e );
}
}

void ui_event_brightnessDec( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      brightnessDec( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Screen1);
//lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
lv_obj_set_width( ui_Spinner1, 53);
lv_obj_set_height( ui_Spinner1, 56);
lv_obj_set_x( ui_Spinner1, -206 );
lv_obj_set_y( ui_Spinner1, -204 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -53 );
lv_obj_set_y( ui_Label1, -207 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"ESP32S3 with 4\" LCD \nCAN Demo");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 60);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, -87 );
lv_obj_set_y( ui_Button1, 192 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFCF704), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button2, 60);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, -18 );
lv_obj_set_y( ui_Button2, 192 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, 72 );
lv_obj_set_y( ui_Button3, 192 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 50);
lv_obj_set_x( ui_Button4, 180 );
lv_obj_set_y( ui_Button4, 192 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF0101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -162 );
lv_obj_set_y( ui_Label2, 230 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"skpang.co.uk 07/25");

ui_version = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_version, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_version, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_version, -19 );
lv_obj_set_y( ui_version, 231 );
lv_obj_set_align( ui_version, LV_ALIGN_CENTER );
lv_label_set_text(ui_version,"LVGL VERSION");
lv_obj_set_style_text_align(ui_version, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightness = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_brightness, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightness, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightness, -175 );
lv_obj_set_y( ui_brightness, 149 );
lv_obj_set_align( ui_brightness, LV_ALIGN_CENTER );
lv_label_set_text(ui_brightness,"Brightness");
lv_obj_set_style_text_align(ui_brightness, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 69 );
lv_obj_set_y( ui_Label4, 194 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"START");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 180 );
lv_obj_set_y( ui_Label5, 192 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"STOP");

ui_brightnessInc = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_brightnessInc, 50);
lv_obj_set_height( ui_brightnessInc, 50);
lv_obj_set_x( ui_brightnessInc, -207 );
lv_obj_set_y( ui_brightnessInc, 192 );
lv_obj_set_align( ui_brightnessInc, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_brightnessInc,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_brightnessInc, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_brightnessInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_brightnessInc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_brightnessInc, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_brightnessInc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_brightnessInc, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessDec = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_brightnessDec, 50);
lv_obj_set_height( ui_brightnessDec, 50);
lv_obj_set_x( ui_brightnessDec, -151 );
lv_obj_set_y( ui_brightnessDec, 192 );
lv_obj_set_align( ui_brightnessDec, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_brightnessDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_brightnessDec, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelbright = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_labelbright, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelbright, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelbright, -207 );
lv_obj_set_y( ui_labelbright, 194 );
lv_obj_set_align( ui_labelbright, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelbright,"+");
lv_obj_set_style_text_font(ui_labelbright, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -154 );
lv_obj_set_y( ui_Label9, 193 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"-");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 465);
lv_obj_set_height( ui_Panel1, 110);
lv_obj_set_x( ui_Panel1, -2 );
lv_obj_set_y( ui_Panel1, -120 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -196 );
lv_obj_set_y( ui_Label8, -153 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"CAN FD");
lv_obj_set_style_text_decor(ui_Label8, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canfdData = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canfdData, 341);
lv_obj_set_height( ui_canfdData, 89);
lv_obj_set_x( ui_canfdData, 50 );
lv_obj_set_y( ui_canfdData, -120 );
lv_obj_set_align( ui_canfdData, LV_ALIGN_CENTER );
lv_label_set_text(ui_canfdData,"00 00 00");

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 465);
lv_obj_set_height( ui_Panel2, 64);
lv_obj_set_x( ui_Panel2, -2 );
lv_obj_set_y( ui_Panel2, -19 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ClassicCANdata = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ClassicCANdata, 324);
lv_obj_set_height( ui_ClassicCANdata, 22);
lv_obj_set_x( ui_ClassicCANdata, 35 );
lv_obj_set_y( ui_ClassicCANdata, -34 );
lv_obj_set_align( ui_ClassicCANdata, LV_ALIGN_CENTER );
lv_label_set_text(ui_ClassicCANdata,"00 00 00");

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -182 );
lv_obj_set_y( ui_Label6, -37 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Classic CAN");

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -215 );
lv_obj_set_y( ui_Label10, -129 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"ID :");

ui_canfdID = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canfdID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canfdID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canfdID, -166 );
lv_obj_set_y( ui_canfdID, 103 );
lv_obj_set_align( ui_canfdID, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_canfdID,"0x7df123");
lv_obj_set_style_text_align(ui_canfdID, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -209 );
lv_obj_set_y( ui_Label12, -105 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Len :");

ui_canFDLen = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canFDLen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canFDLen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canFDLen, -177 );
lv_obj_set_y( ui_canFDLen, -104 );
lv_obj_set_align( ui_canFDLen, LV_ALIGN_CENTER );
lv_label_set_text(ui_canFDLen,"64");

ui_Label11 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -210 );
lv_obj_set_y( ui_Label11, -18 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"ID :");

ui_ccCANID = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ccCANID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ccCANID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ccCANID, 52 );
lv_obj_set_y( ui_ccCANID, -18 );
lv_obj_set_align( ui_ccCANID, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ccCANID,"8");
lv_obj_set_style_text_align(ui_ccCANID, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -205 );
lv_obj_set_y( ui_Label13, 1 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Len :");

ui_ccCANlen = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ccCANlen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ccCANlen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ccCANlen, -177 );
lv_obj_set_y( ui_ccCANlen, 2 );
lv_obj_set_align( ui_ccCANlen, LV_ALIGN_CENTER );
lv_label_set_text(ui_ccCANlen,"8");

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 465);
lv_obj_set_height( ui_Panel3, 70);
lv_obj_set_x( ui_Panel3, -1 );
lv_obj_set_y( ui_Panel3, 69 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -193 );
lv_obj_set_y( ui_Label7, 52 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Transmit");

ui_framecount = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_framecount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_framecount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_framecount, -102 );
lv_obj_set_y( ui_framecount, 80 );
lv_obj_set_align( ui_framecount, LV_ALIGN_CENTER );
lv_label_set_text(ui_framecount,"1234");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -175 );
lv_obj_set_y( ui_Label3, 80 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Frame count :");

ui_clear = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_clear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clear, -87 );
lv_obj_set_y( ui_clear, 194 );
lv_obj_set_align( ui_clear, LV_ALIGN_CENTER );
lv_label_set_text(ui_clear,"Clear");

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_brightnessInc, ui_event_brightnessInc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_brightnessDec, ui_event_brightnessDec, LV_EVENT_ALL, NULL);
uic_brightnessInc = ui_brightnessInc;
uic_brightnessDec = ui_brightnessDec;
uic_canfdID = ui_canfdID;
uic_canFDLen = ui_canFDLen;
uic_ccCANID = ui_ccCANID;
uic_ccCANlen = ui_ccCANlen;
uic_clear = ui_clear;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Spinner1= NULL;
ui_Label1= NULL;
ui_Button1= NULL;
ui_Button2= NULL;
ui_Button3= NULL;
ui_Button4= NULL;
ui_Label2= NULL;
ui_version= NULL;
ui_brightness= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
uic_brightnessInc= NULL;
ui_brightnessInc= NULL;
uic_brightnessDec= NULL;
ui_brightnessDec= NULL;
ui_labelbright= NULL;
ui_Label9= NULL;
ui_Panel1= NULL;
ui_Label8= NULL;
ui_canfdData= NULL;
ui_Panel2= NULL;
ui_ClassicCANdata= NULL;
ui_Label6= NULL;
ui_Label10= NULL;
uic_canfdID= NULL;
ui_canfdID= NULL;
ui_Label12= NULL;
uic_canFDLen= NULL;
ui_canFDLen= NULL;
ui_Label11= NULL;
uic_ccCANID= NULL;
ui_ccCANID= NULL;
ui_Label13= NULL;
uic_ccCANlen= NULL;
ui_ccCANlen= NULL;
ui_Panel3= NULL;
ui_Label7= NULL;
ui_framecount= NULL;
ui_Label3= NULL;
uic_clear= NULL;
ui_clear= NULL;

}
