// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void clear_pressed(lv_event_t * e)
{
	// Your code here
}

void blue_pressed(lv_event_t * e)
{
	// Your code here
}

void start_event(lv_event_t * e)
{
	// Your code here
}

void stop_event(lv_event_t * e)
{
	// Your code here
}

void brightnessInc(lv_event_t * e)
{
	// Your code here
}

void brightnessDec(lv_event_t * e)
{
	// Your code here
}
